The first revision
spine-examples/airport pull request #1
Opened 2020-01-21 12:06 UTC by dmdashenkov

2020-01-31 16:26 UTC, dmdashenkov commented
@armiol, PTAL.

2020-02-02 13:44 UTC, armiol requested changes

2020-02-02 13:44 UTC, armiol commented on .gitmodules
> +	url = https://github.com/SpineEventEngine/config
I would copy this over instead of sub-moduling it.

2020-02-02 13:44 UTC, armiol commented on README.md
>  ### Airplane Supplies Context
I would also put a few words on what each context is.

2020-02-02 13:44 UTC, armiol commented on airplane-supplies/src/main/java/io/spine/example/airport/supplies/AirplaneId.java
> +public final class AirplaneId {
As always, let's document the public API.

2020-02-02 13:44 UTC, armiol commented on airplane-supplies/src/main/java/io/spine/example/airport/supplies/Main.java
> +final class Main {
Consider calling that in a more meaningful way.

2020-02-02 13:44 UTC, armiol commented on airplane-supplies/src/main/java/io/spine/example/airport/supplies/PlaneSupplies.java
> +        public Builder setWhenPreFlightCheckComplete(Instant whenPreFlightCheckComplete) {
I would combine the setters for "when complete" and "how successful it was".

2020-02-02 13:44 UTC, armiol commented on airplane-supplies/src/main/java/io/spine/example/airport/supplies/SuppliesEventProducer.java
> +    private static final Random rand = new Random();
Not sure why not use a secured version.

2020-02-02 13:44 UTC, armiol commented on airplane-supplies/src/main/java/io/spine/example/airport/supplies/SuppliesEvents.java
> +            TypeUrl.of(AntiFrostingCheckComplete.class);
This is not what is is.

2020-02-02 13:44 UTC, armiol commented on airplane-supplies/src/main/proto/spine/example/airport/supplies/supplies_events.proto
> +    string plane_id = 1;
I would make this a typed thing.

2020-02-02 13:44 UTC, armiol commented on takeoffs-and-landings/src/main/java/io/spine/example/airport/tl/PollingClient.java
> + * A client which runs indefinitely pulling data from an external API.
`A client continuously pulling the data from an external API`.

Also, is it `Polling` client or `Pulling`?

2020-02-03 15:19 UTC, dmdashenkov commented
@armiol, PTAL.

2020-02-03 16:30 UTC, armiol approved these changes

2020-02-03 16:31 UTC, merged